# Generated by Django 2.0.13 on 2019-03-30 04:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=500)),
                ('createddate', models.DateTimeField(default=datetime.datetime(2019, 3, 30, 4, 1, 58, 233852, tzinfo=utc))),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
    ]
