# Generated by Django 2.0.13 on 2019-03-30 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedasite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 4, 3, 23, 698149, tzinfo=utc)),
        ),
    ]
