# Generated by Django 2.0.13 on 2019-03-30 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedasite', '0002_auto_20190330_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='createddate',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 4, 5, 1, 744724, tzinfo=utc)),
        ),
    ]
