# Generated by Django 2.0.13 on 2019-03-31 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedasite', '0005_auto_20190330_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('causes', models.TextField(max_length=500)),
                ('symptom', models.TextField(max_length=500)),
                ('remedy', models.TextField(max_length=500)),
                ('link', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 5, 34, 42, 262280, tzinfo=utc)),
        ),
    ]
