# Generated by Django 2.0.13 on 2019-03-31 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedasite', '0006_auto_20190331_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='image',
            field=models.ImageField(default='ayurvedasite/images/no.jpg', upload_to='ayurvedasite/images/mouth.jpeg'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 5, 45, 41, 212837, tzinfo=utc)),
        ),
    ]
