# Generated by Django 2.0.13 on 2019-03-31 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedasite', '0007_auto_20190331_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 6, 33, 19, 651033, tzinfo=utc)),
        ),
    ]
