# Generated by Django 2.0.13 on 2019-03-31 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedasite', '0010_auto_20190331_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 17, 26, 2, 447996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='image',
            field=models.ImageField(default='static/ayurvedasite/images/no.png', upload_to='images/'),
        ),
    ]
