# Generated by Django 2.0.13 on 2019-03-31 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedasite', '0012_auto_20190331_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 17, 55, 4, 643691, tzinfo=utc)),
        ),
    ]
