# Generated by Django 2.0.13 on 2019-03-31 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedasite', '0015_auto_20190331_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 19, 39, 24, 33798, tzinfo=utc)),
        ),
    ]
